### ISSUE TITLE
Invalid Player Data - Singleplayer World Connection

### ISSUE THREAD

**Issue by ViewAccount74** [LunaPixelStudios/Fear-Nightfall#100]
### Describe the Bug

Never happened before, but today upon starting the Fear Nightfall through Curseforge I was hit with "Can't connect to server" (though it's a single player world) for 2 times, and then the next 2 times I received "Invalid Player Data". Both situations threw me into the Servers lobby, searching for servers.

Modpack is pristine, with the small difference that I turned off Carry On. 

Temporary solution: fully restarting the game

Best regards,

### Reproduction Steps

1. Started Fear Nightfall
2. Started the SinglePlayer world
3. Received "can't connect to server"
4. Upon second retry, received "invalid player data"

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v12

**Comment by chorbintime** [comment]
Please send your latest.log file
