### ISSUE TITLE
Bugged horses

### ISSUE THREAD

**Issue by ViewAccount74** [LunaPixelStudios/Fear-Nightfall#101]
### Describe the Bug

All horses are 100% slow. This might be due to my recent post of "Invalid Player Data", but it just took place randomly after restarting the game and playing for an hour. My then horse at some random moment just started being really slow, slower than Steve walking speed, and now all horses are slow (tested 10 horses on a plains field)

### Reproduction Steps

1. Restarted the game after "Invalid Player Data"
2. Played the game normally for 30m - 1h
3. Randomly upon riding my horse it just became extremely slow
4. Tamed multiple horses, all are slow and don't jump far up

### Screenshots and Videos

https://we.tl/t-6igHZCpDyc - video

Post Scriptum: I do however remember seeing this issue before in Vanilla. Not sure what fixed it. Couldn't find any post related to that on the WWW.

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v12

**Comment by chorbintime** [comment]
Please send your latest.log file in your logs folder
