### ISSUE TITLE
Game Crashed (upon first opening)

### ISSUE THREAD

**Issue by fennee** [LunaPixelStudios/Fear-Nightfall#102]
### Describe the Bug

It just crashes every time I open it. I hit play on the Minecraft launcher. It does the Mojang Studios loading bar and it gets to around 99% and it crashes. Please advise or ask me for any extra details you need? Thanks --Harry

### Reproduction Steps

1. I hit play on the Minecraft launcher
2. That's literally it.
3.
...

### Screenshots and Videos

![Screenshot 2024-04-16 at 12 31 07](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/10802674/4aa8bf76-26f3-4e9e-bc0d-33bedf9d45a5)
![Screenshot 2024-04-16 at 12 31 20](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/10802674/06c387fa-e36d-4d2f-ad36-c94103cb7dcd)

### Crash Report or Log

Too long to fit so I pasted in a pastebin: https://pastebin.com/Zz8vh1As

### Operating System

macOS Sonoma 14.2.1

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

43.3.5

**Comment by chorbintime** [comment]
Delete the shaderpacks folder in the game files and retry

**Comment by fennee** [comment]
Thank you! This seems to have worked. However, now when I start world creation in single player it crashes at this stage as well. See crash report here: https://pastebin.com/DrJUtRGL

**Comment by chorbintime** [comment]
## For Mac devices using Apple Silicon/arm (M1/M2/etc.) CPUs
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:
1. Install the `Zulu JDK 17.0.1+12 arm64` build of Java:
Direct download: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=7eb8ee44-ab7f-4afb-9e42-32bd76416400 
2. Download/Install ATLauncher or Prism Launcher (CurseForge Launcher is known to cause issues)
3. In Instance settings > Java, manually specify the following Java path: `/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home`
4. If using ATLauncher, Disable "Use Minecraft-bundled JDK"
5. Launch the game
