### ISSUE TITLE
Immersive Engineering - Fear Nightfall - Diesel Generator issue

### ISSUE THREAD

**Issue by SzalonyScout1** [LunaPixelStudios/Fear-Nightfall#103]
### Describe the Bug

Hi,
I'm currently having an issue with Immersive Engineering mod which is on Fear Nightfall modpack.

The issue is about the "bio-diesel" not filling the diesel generator capacity tank.

The diesel generator has two liquid inputs which needs to be connected, after being connected by fluid pipes nothing happens after that, which makes the generator useful and really huge waste of time.

I've tried all possible ways to make it happen, nothing worked.

### Reproduction Steps

1. Make a Fluid Tank/Silo
2.  Fill in the Bucket of Bio-diesel into Fluid Tank/Silo 
3. Connect fluid pipes into the Inputs of the Diesel Generator
4. Diesel generator **SHOULD** fill in, but it does nothing.
5. Diesel Generator does nothing.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/168301561/16ab4f5f-3091-4d01-8491-fd6a555867f8)
![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/168301561/2bb8e056-b240-4526-8a25-d7cc86b76f18)
![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/168301561/0bc53619-ad84-4dd8-94b0-f88d79b024ae)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

### Other Mods

None.

**Comment by chorbintime** [comment]
Does the Immersive Engineering mod have an update available? If so, try updating it.
