### ISSUE TITLE
Conquest of Immersive Engineering resource pack 404s

### ISSUE THREAD

**Issue by GreatestFool** [LunaPixelStudios/Fear-Nightfall#104]
### Describe the Bug

If you try to download the resource pack, it fails to download.

### Reproduction Steps

1. Go to https://www.curseforge.com/api/v1/mods/678193/files/4271437/download
2. Get JSON 404

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/3003484/a9af299d-835a-4ec1-88af-2debc207ab7b)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

**Comment by chorbintime** [comment]
The resourcepack will be removed in the next modpack update. Thank you for letting us know!
