### ISSUE TITLE
Modpack 404

### ISSUE THREAD

**Issue by keiran-davidson** [LunaPixelStudios/Fear-Nightfall#105]
### Describe the Bug

The Conquest of Immersive Engineering modpack returns a 404 when attempting to download. This is affecting downloading on Linux and other OS's. 

### Reproduction Steps

1. Visit https://www.curseforge.com/minecraft/texture-packs/conquest-of-immersive-engineering
2. Attempt download

### Screenshots and Videos

<img width="622" alt="Screenshot 2024-05-05 at 18 03 09" src="https://github.com/LunaPixelStudios/Fear-Nightfall/assets/85039710/4f5dbf0c-85bb-4d1e-a198-8ff8254fe7cf">

### Operating System

All OS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.3

**Comment by chorbintime** [comment]
https://github.com/LunaPixelStudios/Fear-Nightfall/issues/104#issuecomment-2094346406
