### ISSUE TITLE
Entities ticked

### ISSUE THREAD

**Issue by digitalready-ChrisT** [LunaPixelStudios/Fear-Nightfall#106]
### Describe the Bug

Everytime I play the game there is a moment where every few seconds or minutes thousands of eities are ticked and said to be skipped

### Reproduction Steps

1. Just play
2.
3.
...

### Operating System

Window 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Bmcv52

**Comment by chorbintime** [comment]
Can you please be more specific?

Also, are you sure you're reporting this in the right place? The modpack version you listed is "Bmcv52", but that doesn't exist.
