### ISSUE TITLE
Can't sleep

### ISSUE THREAD

**Issue by ParkSeonDann** [LunaPixelStudios/Fear-Nightfall#107]
### Describe the Bug

My friends and I can't sleep, even if it's night or there's a storm. We tried different types of beds and still couldn't.

### Operating System

Windows 11 pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear NightFall

**Comment by chorbintime** [comment]
this is an intended feature. please read the tutorial quests in the questbook
