### ISSUE TITLE
Can't aquire sharp claw from Biomancy 2

### ISSUE THREAD

**Issue by kajzerabagieta** [LunaPixelStudios/Fear-Nightfall#108]
### Describe the Bug

No mob seems to be dropping sharp claw/sharp fang thus you cannot even progress in game. I'm playing on the newest version on mutliplayer on PC. Cannot even find anything if that's disabled, so please help me :(

### Reproduction Steps

1. Kill any mob that's supposed to drop it
2. No drops :(
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

**Comment by chorbintime** [comment]
What launcher are you using?

Can you send your latest.log file, from the logs folder?

**Comment by kajzerabagieta** [comment]
I'm using Sklauncher 
[latest.log](https://github.com/user-attachments/files/15518691/latest.log)

**Comment by kajzerabagieta** [comment]
I'm using Sklauncher  
[Uploading latest.log…]()

**Comment by kajzerabagieta** [comment]
I'm using Sklauncher 
[latest.log](https://github.com/user-attachments/files/15518745/latest.log)

**Comment by chorbintime** [comment]
SKLauncher does not install mods or modpacks correctly. We offer no support for piracy whatsoever. Please reinstall on ATLauncher with a proper Minecraft account.
