### ISSUE TITLE
Getting pulled down whenever jumping, falling or using ladders and ropes

### ISSUE THREAD

**Issue by Xplorosaurus** [LunaPixelStudios/Fear-Nightfall#109]
### Describe the Bug

This happened to me the first time now while playing Fear Nightfall and it happened out of the blue. Whenever i try to climb a ladder or rope or literally anything else i get pulled downwards. I thought it's due to the evoker thingy but it wasn't. Set my game to peaceful and even used spectator mode to look for certain mobs but all it did is pull me down below bedrock where it suddenly stopped. It's like I'm holding the sneak key constantly but it's not that. Even after a restart it still happened 

### Reproduction Steps

1. Get ladder/rope/scaffolding 
2. Climb ladder/rope/scaffolding 
3. Try if the same happens to you
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v11.5

**Comment by chorbintime** [comment]
How did you install the modpack?

**Comment by Xplorosaurus** [comment]
Via FTB. But i can say now, after i reinstalled FTB the bugb is gone, for now

**Comment by Kzatarii** [comment]
Same is happening to me in two worlds. What is FTB? I have my mods downloaded from curseforge. If i delete the mods and redownload them will my worlds be gone?

**Comment by Xplorosaurus** [comment]
FTB is feed the beast modloader. I simply made a copy of the save file from my world and saved it elsewhere before reinstalling. After that i copied it back into the folder and restarted the modpack

**Comment by chorbintime** [comment]
Reinstall the modpack completely fresh on ATLauncher and copy over your saves folder.
