### ISSUE TITLE
Tree leaves bug texture

### ISSUE THREAD

**Issue by barri16** [LunaPixelStudios/Fear-Nightfall#110]
### Describe the Bug

Since I have started the game I have noticed a bug in the texture of the leaves of the trees, it looks very annoying and evident (Image 1). I have thought that it would be a failure of one of the resource packs and I was right, specifically of the pack "Ashen_1.4.3_1.19.2". When I remove it, this texture problem is solved, but another problem appears in the texture of certain leaves of the trees (Image 2). I would like to know if there is any solution or something I can do to not have this problem, thank you very much.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Image 1](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/173397642/620963f5-861c-446b-9642-4ff6736dd829)
![Image 2](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/173397642/40cc8ff0-a70c-4309-a1c5-d9f8b04f3e99)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v14

**Comment by chorbintime** [comment]
put your graphics settings on fancy, and dont remove any resourcepacks
