### ISSUE TITLE
Getting pulled down when jumping

### ISSUE THREAD

**Issue by Kzatarii** [LunaPixelStudios/Fear-Nightfall#111]
### Describe the Bug

Like i wrote on a comment on another report, this has happened to me in two worlds already. First everything is normal and we get to play a lot in LAN with my friend without this issue. I do nothing differently but all of a sudden we both get pulled down when we are (for example) jumping. 
I moved the worlds to another folder, deleted the modpack in Curseforge, re-downloaded it and moved the worlds to the new saves folder. It did not work. I would attach a video but the file size is too big,

### Reproduction Steps

1. Play the game for a long time
2. Bug happens?
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v14

**Comment by chorbintime** [comment]
We offer no support for LAN. Please host a server normally through the serverpack provided on the modpack's Curseforge page.
