### ISSUE TITLE
Main menu outlines not disappearing when in world

### ISSUE THREAD

**Issue by Pulkus** [LunaPixelStudios/Fear-Nightfall#113]
### Describe the Bug

The outline of the main menu text for fear-nightfall doesn’t disappear when joining a world. Also doesn’t appear over inventory hud for some reason.
![IMG_7064](https://github.com/user-attachments/assets/db3c2ddd-fc8c-4aa8-b797-f31be5301ed0)

### Reproduction Steps

1. Update to version 15
2. Host a world
3. Profit
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/a80ce32a-db7b-4bcf-8cb8-29a32b8ea96b)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v15

### Other Mods

Essential

**Comment by Pulkus** [comment]
The version I found out later is actually 1.19. Additionally, the issue fixed itself when I entered the nether and left.

**Comment by chorbintime** [comment]
Remove the Essential mod. It is completely incompatible and the mod itself has a ton of issues such as world corruption. There is no reason to use Essential in any modpacks.

We already include a custom version of the e4mc mod in all of our modpacks. To host a world easily, press escape ingame and go to "Open to LAN", then click "Share World". You can also follow [this](https://github.com/chorbintime/LPS-readme/wiki/1.20.1) guide for properly selfhosting a server.

**Comment by Pulkus** [comment]
> the 

I didn't know about e4mc before this. I'll probably use that instead of essential from now on
