### ISSUE TITLE
end of herobrine might be bugged

### ISSUE THREAD

**Issue by Rowdeezy** [LunaPixelStudios/Fear-Nightfall#114]
### Describe the Bug

I'm hosting a budget server of fear nightfall(7ram) through bisect, not even a week old yet. The issue i'm having is with the configs for herobrine, the other night I was online and I seen him for the first time, he had no nametag and made no noise so I always got spooked when seeing him... fast foward a day or 2 irl later and now he has a nametag when he spawns and also he makes the noises of other mobs, rly the creeper I think... that growling noise... idk if I messed something up but I have no idea what to do, he spawns like every 2 mins, I tried changing the time in his config(the orange numbers) but it doesn't seem to affect him at all, neither does the client name tag option...

### Reproduction Steps

1.host a server through bisect
2.casual gameplay
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

### Other Mods

I changed the the simple voice chat mod to a different 1.19.2 version because it wasn't working with the version installed but these herobrine issues were happening before I did that

**Comment by chorbintime** [comment]
follow the questbook for how to get rid of herobrine
