### ISSUE TITLE
Born in Chaos projectile weapons not working.

### ISSUE THREAD

**Issue by Reekesz** [LunaPixelStudios/Fear-Nightfall#115]
### Describe the Bug

The Staff of Magic arrows, intoxicating bomb, pumpkin pistol, etc do not fire projectiles while in the overworld. While in the nether they seem to work about 50% of the time.

### Reproduction Steps

1. Equip born of chaos projectile weapons
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
if updating the mod to the latest version doesnt fix it, then report it to the developers of the born in chaos mod
