### ISSUE TITLE
Some mobs are disabled/doesn't spawn 

### ISSUE THREAD

**Issue by BistoX** [LunaPixelStudios/Fear-Nightfall#116]
### Describe the Bug

Some mobs from differents mod doesn't spawn.
For exemple the flesh Carcass from sons of sins and the Pumpkin Spirit from the mod born in chaos.
I' don't see error in the console log and i don't find any references in the config file for disabling this entities

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/41471201-ee4e-406d-9219-ed1a669e35c2

### Operating System

w10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
this is intentional. the mobs are removed via the you shall not spawn mod
