### ISSUE TITLE
Mod Config Incompatibility: Equipment Passed Off to Herobrine and Deleted

### ISSUE THREAD

**Issue by Googlenomicon** [LunaPixelStudios/Fear-Nightfall#117]
### Describe the Bug

The Quark mod inventory management settings are incompatible with the From the Fog mod. It's unlikely to come up, but can ruin longstanding runs. If you shift right click (or possibly left click) Herobrine (which can happen since he can force you to look at him if you accidentally bump into him), you'll end up passing off all your armour to him and said equipment will be subsequently deleted. This issue is present in both the ATlauncher and Curseforge version.

This is fixable by modifying the config and disabling the Quark management options. I don't know which one specifically, as I simply turned them all off to fix the issue, but I would suspect it's the quick armour swapping option. If it is possible, I would like to request that a future update in this modpack disables the problematic Quark settings by default.

### Reproduction Steps

1. Wait for Herobrine to spawn, then back up into him.
2. When he forces you to look at him, hold shift and then right click (or left click if that doesn't work)
3. Your armour and offhand item will be given to Herobrine, and subsequently deleted when he despawns.

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

V15

**Comment by chorbintime** [comment]
will be fixed in the next modpack update, thanks
