### ISSUE TITLE
Spawn eggs broken

### ISSUE THREAD

**Issue by jellyfish-org** [LunaPixelStudios/Fear-Nightfall#119]
### Describe the Bug

When in creative mode many of the modded spawn eggs don't work. Some produce sounds (the sons of sins, born in chaos, box of horrors, etc.) but none of them actually spawn the entities. So far the mods I've found with bugged eggs are sons of sins, born in chaos, box of horrors, fallen monsters, the end of herobrine, and undead unleashed.

### Reproduction Steps

1. Start game in creative mode
2. grab spawn egg from inventory
3. use spawn egg

### Operating System

Mac

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
this is intentional. the mobs are disabled via the you shall not spawn mod
