### ISSUE TITLE
Crafting Table/Furnace Crash

### ISSUE THREAD

**Issue by Babanine** [LunaPixelStudios/Fear-Nightfall#12]
### Describe the Bug

If you sprint jump and then place down a crafting table/furnace while holding it with both hands the game crashes.
Happening to a friend aswell.

### Reproduction Steps

1. Shift right click a crafting table/furnace to pick it up
2. Sprint jump
3. Place down crafting table while sprint jumping

### Crash Report or Log

https://pastebin.com/JUECrQYy

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v5

### Other Mods

no

**Comment by SHXRKIIE** [comment]
Should hoepfully be fixed in next update, i couldnt recreate it but yeah
