### ISSUE TITLE
White Moon effect not working?

### ISSUE THREAD

**Issue by MagpieIsPlaying** [LunaPixelStudios/Fear-Nightfall#121]
### Describe the Bug

Hello! I'm Adrian. 
First of all, forgive my English. Second, I'll start with the doubts: I hope this is not a false allarm, but during a night, it appeared the following message:
"A White Moon has appeared!
I got informed and all I could find about this event is that this moon makes the current night serene (hopefully, i didnt miss any info about it).
Although, even if there was the white moon, the night still filled up with mosters like a regular night (they even blew up my entrance and break into the house lol).
So, I wanted to report this and wanted to know if there are some mods in the modpack that prevent or obstruct the effects of the white moon in the game.
Thank you for helping clearing my doubts.
Have everyone a good day <3

P.S.: I can't make screenshots, so I hope I made myself clear enough ^^"

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

### Other Mods

No addition made

**Comment by chorbintime** [comment]
will be looked into, thanks. its likely that some mods arent taking into account for the moon effect
