### ISSUE TITLE
Hexerei and Immersiv Bug

### ISSUE THREAD

**Issue by KumikoTsukimi** [LunaPixelStudios/Fear-Nightfall#122]
### Describe the Bug

Hello, I said something a while ago about The signs from herobrine not working well aside from that In my Current Fear nightfall server with some friends Hexeri now wont work.. Im trying to make rain go away candles and the dipper wont dip for some reason also. on the last server I was it worked but Immersiv engenierring didnt worked and It still doesnt.. Im confused

### Reproduction Steps

1.Made Thicc potion in the hexerei cauldron
2.added dipper and candles
3.CANDLE WONT DIP ):

also for the imersiv engerniering one. I had a water wheel tzhat powerd something and It didnt power The power wasnt working Not even Creativ power worked-
...

### Operating System

windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
Please report these issues to the individual mod authors
