### ISSUE TITLE
Self-hosted server issues

### ISSUE THREAD

**Issue by SleekSkydog50** [LunaPixelStudios/Fear-Nightfall#123]
### Describe the Bug

Unable to launch private server, I downloaded the files using the curseforge app and have not altered any file yet. I am unfamiliar with a file running using powershell, was this supposed to be a batch file?

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/5b192ff4-a9ba-4f7f-aef4-08acfa825664)

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v15

**Comment by chorbintime** [comment]
Please follow [the guide](https://github.com/chorbintime/LPS-readme/wiki/1.20.1)
