### ISSUE TITLE
Stuck on mojang loading screen opening fear nightfall via ATlauncher on MAC

### ISSUE THREAD

**Issue by Kuto5** [LunaPixelStudios/Fear-Nightfall#125]
### Describe the Bug

As the title says, i keep getting stuck on the loading screen no matter what i do. I open fear nightfall via AT launcher and i get some errors in the console and then get stuck. Im on an M3 macbook pro!

### Reproduction Steps

1. open fear nightfall via AT launcher (FOR MAC)
2.Wait for it to load
3. get stuck on mojang loadign screen
...

### Screenshots and Videos

<img width="842" alt="Screenshot 2024-08-22 at 7 35 12 pm" src="https://github.com/user-attachments/assets/e03f0195-e6ad-4099-84fe-3fc66a7329c7">

### Crash Report or Log

https://paste.atlauncher.com/view/054419e7-8b67-4110-b89f-961c184ebc3a

### Operating System

Mac Sonoma

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

**Comment by SHXRKIEgg** [comment]
You are on mac so i cant really test hot to fix it unfortunately and not really meant to be played on a mac
