### ISSUE TITLE
Mobs Spawn

### ISSUE THREAD

**Issue by Yozora154** [LunaPixelStudios/Fear-Nightfall#126]
### Describe the Bug

While I play, some mobs don't spawn, and most take ages to appear, I've been playing for 10 hours and I've only seen a few creatures from the modpack, the rest were the standard mobs.

### Reproduction Steps

1. just start new game
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v15

### Other Mods

Tenebrous lands

**Comment by SHXRKIEgg** [comment]
try v16
