### ISSUE TITLE
Fps drop after looking at altar(Hexerei) in survival mode

### ISSUE THREAD

**Issue by Gkitkatus** [LunaPixelStudios/Fear-Nightfall#128]
### Describe the Bug

After i placed altar in the overworld and my fps suddenly droped to 1-2. After further testing i found out this:
1) Fps droping only in survival mode
2) It's problem probably not in my hardware. Played with 2 friends through lan and everyone had this issue when i placed altar
3) Fps droping only when you directly looking at it
4) Placed shadow book still working normaly if you manage to not look at the altar

### Reproduction Steps

1.Place altar in the otherworld
2.Be sure to be in survival mode
3.Look at it directly
...

### Screenshots and Videos

https://github.com/user-attachments/assets/399dc0ea-c9c4-4eaa-9cea-8310b06ea89f

### Crash Report or Log

https://gist.github.com/Gkitkatus/fa65ba44d0cf703899d588ad1ff3ab41

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v16

**Comment by Magician-Dev** [comment]
It's a bug that some types of render cause. Check if you have the "The Man From The Fog" mod installed, since that one is the most common mod for this cause. If you don't have it installed, or it still lags nontheless then try disabling mods with custom renders.

**Comment by SHXRKIEgg** [comment]
It seems Siren Head is causing the issue, remove that mod
