### ISSUE TITLE
Shy Guy Audio bug

### ISSUE THREAD

**Issue by DarthBanana0428** [LunaPixelStudios/Fear-Nightfall#129]
### Describe the Bug

So I'm building my base and for some reason the shy guy scream is playing over and over with about a 20 second reprieve and its not just the sound playing back to back its overlapping about 4-6 times over constantly and i dont know if its just this one spot or what if so i will glady move my base.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v16.5

**Comment by SHXRKIEgg** [comment]
leave the area and come back, he would only be screaming if someone looked at him
