### ISSUE TITLE
Shy Guy Scream earrape

### ISSUE THREAD

**Issue by Magician-Dev** [LunaPixelStudios/Fear-Nightfall#130]
### Describe the Bug

I'm trying to build my base on a plains biome and i was doing ok until day 1 (after day 0) since the Shy Guy Scream sound started actively playing nonstop and overlapping with each other and there was nothing. NO ENTITY. I decided to disable the shy guy mod for myself, but this is something that really should NOT be happening, the game is just audibly unplayable on the full "stable" release of the modpack.

### Reproduction Steps

1. Play the game normally (Complete quests, build a base, etc)
2. Wait (I think it's RNG based, i actually have NEVER seen the monster so i don't know when it happens)
3. LOWER THE VOLUME
...

### Screenshots and Videos

https://github.com/user-attachments/assets/51841ca9-a929-4a4e-b9ba-9ced72326f00

### Crash Report or Log

(Blank)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v16.5 HF

### Other Mods

(Blank)

**Comment by Jackdanbea** [comment]
Yeah currently having the same issue happen to me

**Comment by Magician-Dev** [comment]
> Yeah currently having the same issue happen to me

Yeah, and let's not forget about the hard to destroy reptile that spawned, fell into my trap and is also making nonstop noises my gosh what have they actually done to this modpack lmao

**Comment by Jackdanbea** [comment]
> > Yeah currently having the same issue happen to me
> 
> Yeah, and let's not forget about the hard to destroy reptile that spawned, fell into my trap and is also making nonstop noises my gosh what have they actually done to this modpack lmao

Funny you say that as it happened to me last night 😭

**Comment by SHXRKIEgg** [comment]
Not sure what you set your volume to but the default sounds fine to me
