### ISSUE TITLE
Hard To Destroy Reptile doesn't despawn, causes lag and breaks unintended blocks

### ISSUE THREAD

**Issue by Magician-Dev** [LunaPixelStudios/Fear-Nightfall#131]
### Describe the Bug

The ""Hard to destroy reptilo"" does not seem to follow normal mob despawning and justs stands in my trap screaming for help. He does not go away any time soon. Let's also not forget the LAG he causes while he's screaming in agony: My game went from 130 fps straight to 60 fps. He also destroys blocks he should not destroy. I was looking for my corpse after getting killed by the flying bird thing from the Spore mod and the reptile broke through the (normally) indestructible wall of the cube structure that spawns everywhere and proceeded to chase me for 3 biomes after getting me in water. And then he GAVE me the blocks, which are essentially bedrock and you could place them anywhere. Of course it's on the player to not place it right on their doorway but all of this really really should not happen in a "stable" release of a modpack. I completely understand it's meant to be challenging, but challenging doesn't mean it should be unfair and destroy your ears on the way through.

### Reproduction Steps

1. Make a trap
2. Let the reptile fall in
3. Lag

Blocks bug:

I think this was pure luck that it spawned inside the structure.

### Screenshots and Videos

https://github.com/user-attachments/assets/6873b09b-cc4d-4ed4-9c9f-d70b1bc69736

### Crash Report or Log

(Blank)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v16.5

### Other Mods

Shy Guy disabled

**Comment by SHXRKIEgg** [comment]
Will remove in next update
