### ISSUE TITLE
TPS Problems

### ISSUE THREAD

**Issue by Magician-Dev** [LunaPixelStudios/Fear-Nightfall#132]
### Describe the Bug

I'm having problems when breaking blocks and other TPS-related things. Ghost blocks are really, **really** common now. Grass also takes up to a second to destroy after the block below it has been destroyed. Mobs also are really laggy and inconsistent, sometimes presenting no threat and other times stopping and rush attacking suddenly and making you lose all of your health + get different effects applied like the marker, mycelium infection, etc. The game has become unplayable with all of these indestructible mobs, eardrum destruction and TPS issues. Please fix this as soon as possible, if the mobs attack inconsistenly and i get stuck between blocks, the game is really hard to play.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/7942e364-b68a-41ee-bc0e-bd79701c0eeb

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v16.5

### Other Mods

Shy Guy disabled
Siren Head config tweak so he doesn't destroy my house

**Comment by Magician-Dev** [comment]
Not to mention the TPS problems got even worse: Enemies were now tremendously RNG based and i had to wait up to 6 SECONDS for a block to get broken.

**Comment by SHXRKIEgg** [comment]
Update to v17

**Comment by Magician-Dev** [comment]
Thanks!
