### ISSUE TITLE
Mask possession

### ISSUE THREAD

**Issue by WillyWonkz88** [LunaPixelStudios/Fear-Nightfall#133]
### Describe the Bug

I have no way of removing the mask on a multiplayer server a wishing for a way to remove the mask on a multiplayer server

### Reproduction Steps

1. Just get possessed by the mask
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

The latest version

**Comment by SHXRKIEgg** [comment]
dont put on the mask in the first place lol, your gonna have to die
