### ISSUE TITLE
Animal not giving animal fats

### ISSUE THREAD

**Issue by 0dys-05** [LunaPixelStudios/Fear-Nightfall#134]
### Describe the Bug

Trying to get animal fat to craft book of shadows to progress with quest, but the animals (Cows, Pigs, Chicken & Llama) I killed so far has yet to drop animal fat. 
All that was drop was animal carcass which I used the butcher knife with and without the hook and yet still no animal fat. 
Tried roasting the carcass on top of a campfire still no animal fat.
Am I to assume that the drop rate of animal fat is less than 10%?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

Fear Nightfall-v17

**Comment by SHXRKIEgg** [comment]
update to latest
