### ISSUE TITLE
cant chop trees

### ISSUE THREAD

**Issue by jesperez21** [LunaPixelStudios/Fear-Nightfall#135]
### Describe the Bug

cant chop trees

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v17.5 HF

**Comment by chorbintime** [comment]
please be more specific or provide a video

**Comment by jesperez21** [comment]
It looked like an area where I spawned didn’t let me chop tress or destroy blocks but it was fixed when we just moved further away.

**Comment by jesperez21** [comment]
But recently the portal with the glow stone won’t turn on with the water bucket is that a bug?

**Comment by chorbintime** [comment]
> It looked like an area where I spawned didn’t let me chop tress or destroy blocks but it was fixed when we just moved further away.

its because you were in spawn



> But recently the portal with the glow stone won’t turn on with the water bucket is that a bug?

please follow the questbook
