### ISSUE TITLE
Constant structure generation - The Stairwell mod

### ISSUE THREAD

**Issue by Risingia** [LunaPixelStudios/Fear-Nightfall#137]
### Describe the Bug

Just started a server with the latest version, 17.5hf and I love it. Overall i've enjoyed the additions in recent changes and introduced the modpack to some friends. I've noticed that the Stairwell structure continues to spawn around us and has begun overlapping with preexisting features. I noticed on the comments of the OG mod page on Forge there are several people listing the same complaint. Attached are two photos of our spawn, at first it was just the first stairwell that our base is built on top of

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-10-10_22 21 00](https://github.com/user-attachments/assets/cbaa2175-1273-4fec-b753-eafedf7d6bad)
![2024-10-10_22 24 07](https://github.com/user-attachments/assets/fdbc9e2c-0d05-4f9d-a22b-0a1ecdf82658)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

17.5hf

### Other Mods

none

**Comment by chorbintime** [comment]
try reinstalling the modpack, or playing the 1.20.1 version instead when it releases on Halloween
