### ISSUE TITLE
trying to play the 1.20,1 V of the modpack buts it 1.19.2

### ISSUE THREAD

**Issue by Evilteen18** [LunaPixelStudios/Fear-Nightfall#139]
### Describe the Bug

i ben trying but it keeps going to 1.19.2 idk what to do

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

V18

**Comment by chorbintime** [comment]
The 1.20.1 pack isnt released yet
