### ISSUE TITLE
Herobrine boss fightt

### ISSUE THREAD

**Issue by SycoSavage** [LunaPixelStudios/Fear-Nightfall#14]
### Describe the Bug

We tried spawning Herobrine in the Aether using a nether star and the sinful totem and it doesn't do anything and we have the totem in the correct orientation as well.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

4.5

**Comment by SHXRKIIE** [comment]
Update the modpack
