### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by midoriheishi** [LunaPixelStudios/Fear-Nightfall#140]
### Describe the Bug

when trying to start the game it loads the mods then it just shuts down

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://mclo.gs/QKdE2J8

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.1

**Comment by SHXRKIEgg** [comment]
Error is atio6axx.dll+0x1ca1e2e
Means you need to update your drivers
