### ISSUE TITLE
Multiplayer null nbt bug

### ISSUE THREAD

**Issue by westbot657** [LunaPixelStudios/Fear-Nightfall#141]
### Describe the Bug

This error appears when trying to join a server or LAN world:
Internal Exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128471_(String)" because "nbt" is null

### Reproduction Steps

1. Start a server/LAN world without changing any settings or world options
2. have someone else try to join it
3. error message appears after the "Joining world" message. other player (if LAN) or console (if server) will see you joined and left immediately

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v1.0.1

**Comment by SHXRKIEgg** [comment]
Remove Critters n' Crawlers mod, will be fixed in next update
