### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by gefeshka38** [LunaPixelStudios/Fear-Nightfall#142]
### Describe the Bug

firstly i launched minecraft and everything was ok but after i tried to enter the worl and since then game crashes after loading mods
i`ve seen similar to my issue that was closed 2 days ago but i tried to update my drivers but it slill crashes 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![изображение](https://github.com/user-attachments/assets/8d11f771-df65-4c63-ac38-c059307b2445)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.2

**Comment by nvb-uy** [comment]
Please update your GPU drivers
