### ISSUE TITLE
Vivecraft shaders issue

### ISSUE THREAD

**Issue by Arrow2025** [LunaPixelStudios/Fear-Nightfall#145]
### Describe the Bug

Vivecraft has an issue with the customised shaders for this pack. It causes the HMD to have a very bad crosseye effect. only way to get it to go away is turning the shaders off completely.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.2

**Comment by chorbintime** [comment]
You can try updating the Vivecraft mod. If the issue persists, you should report the issue to the mod author.
