### ISSUE TITLE
low TPS, fear nightfall v18

### ISSUE THREAD

**Issue by law243** [LunaPixelStudios/Fear-Nightfall#146]
hi, ive installed fear nightfall v18 (latest version of the legacy compaign) on a server. We are only 4 players but it has been giving many problems regarding TPS. Server's ram and cpu are only at 20ish%, do you know what could cause this problem and how to solve it? someone told me that the issue could be due to high mobs/entities.. could i solve it by installing a specific mod to add a entity cap?

**Comment by nvb-uy** [comment]
Can you please send a spark profiler?

**Comment by law243** [comment]
> Can you please send a spark profiler?

yep, https://spark.lucko.me/5adIkeLGxE i hope this works.. also from the regular modpack i added 'the one who watches' and 'beware the rain' i hope they are not causing the issue. from what i can see, there are too many 'falling_blocks' (200) and sometimes the MSPT are really bad. (its like having TPS lag spikes basically, they are not constantly bad)

**Comment by nvb-uy** [comment]
v18 is no longer supported, please update to RoC
