### ISSUE TITLE
Consistent freezing/hanging

### ISSUE THREAD

**Issue by RekoHart** [LunaPixelStudios/Fear-Nightfall#147]
### Describe the Bug

Game will freeze. I am able to move around, but new chunks won't load in, inventories cannot be opened, interactive blocks like buttons or levers or doors no longer work. Sometimes the game recovers after a lengthy period, sometimes it never recovers and I have to kill the process.

Error like this shows in console when issue occurs, followed by hundreds of lines of code:
[14:41:50] [ModernFix integrated server watchdog/ERROR]: A single server tick has taken 40001, more than 40000 milliseconds

In addition to the log provided in the below section, which was the most recent occurrence as of this report, here are a few more from previous times if it helps to track down the source
https://gist.github.com/RekoHart/e548b44a6ccc244de15ddc3682941c26
https://gist.github.com/RekoHart/a59b77b51a3a7f56c784899fdf6a1cef
https://gist.github.com/RekoHart/6289783a0d6283a362ebcd0138f14899

I have about a dozen more of these if needed.

### Reproduction Steps

Cannot be forcibly reproduced. Sometimes the game hangs while I am doing nothing at all/AFK, sometimes in the middle of combat, sometimes just in the timeframe between closing a chest and then trying to open the door a few blocks down

### Crash Report or Log

https://gist.github.com/RekoHart/b6315199b3ebf35bd1c48ece4f872b52.js

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v1.0.0 - v1.0.5

### Other Mods

None. I have tried to add a tick hanging killer like Neruina right before this most recent crash but that didn't work and the issue continued.

**Comment by RekoHart** [comment]
I swapped my world to a Bisect server incase it was my hardware giving issue and got my first crash. Hopefully this gives better insight. I will add further comments with future crashes

https://gist.github.com/RekoHart/fb15bb0d5f71155f8333a06093910b09

**Comment by nvb-uy** [comment]
Will look into getting a fix for this, as the mod hasn't updated and due to it not being a tick error and rather the server hanging sadly Neruina wouldn't help

**Comment by RekoHart** [comment]
Thank you. :)

If you need any more logs, let me know.

**Comment by nvb-uy** [comment]
Fixed in v1.0.8 with a temporary fix (removed the mod :p)
