### ISSUE TITLE
The Hordes disabled curing villagers

### ISSUE THREAD

**Issue by RekoHart** [LunaPixelStudios/Fear-Nightfall#148]
### Describe the Bug

Not really a bug, but adding The Hordes mod disabled being able to cure villagers period.

Reporting this here to find out if this was intentional or if we can expect the default config to be switched to allow villager curing again.

### Reproduction Steps

1. Zombify villager
2.Try to cure
3.No dice
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.5

### Other Mods

None

**Comment by nvb-uy** [comment]
Intended, you're supposed to protect villagers now as hordes will attack them.

**Comment by RekoHart** [comment]
Thank you for the update :)
