### ISSUE TITLE
All the issues ive come across so far.

### ISSUE THREAD

**Issue by Aphephobia** [LunaPixelStudios/Fear-Nightfall#149]
### Describe the Bug

------- EDIT: Theres also no way to leave the end in the current build. End Crystals are not craftable etc etc.

Horror Element Mod - Atmosphere Block resets players day counter back to zero when triggered making the quests that require certain days pass to spawn mobs not work and people getting confused. Players also being able to pick up and break these blocks to reset night to day letting them abuse it.

Skeleton Creeper, Magma cube, Blaze textures not aligning correctly.

EEEAB's Mob Mod - The Eye of Bloody Altar wasnt working for me and others ive seen mention it in the discord. When reading the Mod's own discord chat it seems the Dev is aware of the issue and told someone to downgrade to .9 of the mod in 1.20.1 which I did and the eye works for me now. https://www.curseforge.com/minecraft/mc-mods/eeeabs-mobs/files/5392432 that link is the downgraded version I used to fix the problem for myself.

Theres also a dupe with Sons of Sin Urns while using the ability to pick up items with the Carryon Mod.

Also a dupe with Curios and Travelers Backpacks.

### Reproduction Steps

Sons of Sins Dupe (Can only dupe Ether Ashes)

1. Place Urn with Ether Ashes inside it.
2. Pick up with whatever your Carryon hotkey is.
3. As its being picked up it also drops one on the ground duping it.

Travelers Backpack Dupe
1. Put backpack in the Curios free slot.
2. Put backpack in the Cruios back slot.
3. Open backpack using Travelers Backpack hot key.
4. Put anything you want duped inside/Close backpack.
5. Unequip both backpacks manually.
6. Open backpacks one at a time taking the items out of each.
7. Repeat 1-6

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.5

**Comment by nvb-uy** [comment]
The altar issue is fixed on v1.0.6, please make separate issues for each issue and don't make multiple in 1, as it's hard to track.
