### ISSUE TITLE
Walking into Herobrine gives off weird sound bugs and the screen turns black + Herobrine still spawns immortal Husk baby

### ISSUE THREAD

**Issue by Liverstyle** [LunaPixelStudios/Fear-Nightfall#15]
### Describe the Bug

Herobrine spawns the Husks.
When touching herobrine the screen becomes black.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-11-06_19 59 08](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/130424951/5ace5a08-e945-42e4-836f-5a1ddf928519)
![2023-11-06_19 52 39](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/130424951/509df1e3-669e-42bc-8a92-5f066baaccda)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V6.

**Comment by SHXRKIIE** [comment]
you are not on v6 since husks are still there
