### ISSUE TITLE
Hordes dont seem to spawn every 5 days like the settings show.

### ISSUE THREAD

**Issue by Aphephobia** [LunaPixelStudios/Fear-Nightfall#150]
### Describe the Bug

Horde update was around my ingame day of 53, current ingame day is 70. Ive had one horde spawn since. Settings say they should spawn every 5 days.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.5

**Comment by nvb-uy** [comment]
Hordes are delayed so that's why you didn't get it after a few days, this is an issue caused by you updating from an older version. It should keep going normally, let me know if you have further issues.

**Comment by Aphephobia** [comment]
Its ingame day 76 now. On day 75 it acted like a horde was coming but nothing ever spawned. I wasnt able to use a bed because it was saying a horde was coming. Thats my only indicator that a horde tried to spawn but didnt.

**Comment by Enterprise12nx01** [comment]
i havent experienced any hordes either
