### ISSUE TITLE
Still going to be stuck in the End.

### ISSUE THREAD

**Issue by Aphephobia** [LunaPixelStudios/Fear-Nightfall#151]
### Describe the Bug

Theres no recipe to make End Crystals which is needed for crafting the Eternal Crystal which is used to light the Better End return portal. Most Better End recipes dont show up in the JEI also to use in the Altar. I was able to make the Runed Flavorite which is used to make the portal frame by looking the recipe up online.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.6

**Comment by nvb-uy** [comment]
Fixed 1.0.7
