### ISSUE TITLE
Horror Elements Mod

### ISSUE THREAD

**Issue by Aphephobia** [LunaPixelStudios/Fear-Nightfall#152]
### Describe the Bug

The Atmosphere block from Horror Elements Mod is still ingame and going to mess with peoples games. When they are triggered they reduce player day counter to zero. Which is going to cause people to be confused as to why the Boss mobs for chapter 2 arnt spawning if they trigger these without knowing what it does. Causing people to not progress correctly in the campaign.

Players can also dig up these blocks and abuse them.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.0.6

**Comment by nvb-uy** [comment]
Fixed in v1.0.8
