### ISSUE TITLE
in game voice chat isnt working

### ISSUE THREAD

**Issue by DP-Terror** [LunaPixelStudios/Fear-Nightfall#154]
### Describe the Bug

the in game voice chat isnt working and everytime we try and connect our mics to it it shows that it isnt connected when our mics are connected

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

fear nightfall remains of chaos v1.0.7 beta

**Comment by chorbintime** [comment]
Please follow the [voice chat setup guide](https://modrepo.de/minecraft/voicechat/wiki)
