### ISSUE TITLE
Pumpillger task: the location of prisoner

### ISSUE THREAD

**Issue by VictorSPM** [LunaPixelStudios/Fear-Nightfall#16]
### Describe the Bug

not an issue but just want to know The task is so unclear i went to the coordinates and I only see an island above the coordinates but when I got up there is nothing but a skeleton on a horse,I killed it cuz its not like he is saying he is the prisoner. Like what do I do any guide?

### Reproduction Steps

1. Found the pumpkinillger
2. Did the ritual, got the coordinates
3. went to the coordinates and killed a skeleton
...

### Operating System

Window 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V6

**Comment by SHXRKIIE** [comment]
[Report to the mod d](https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest)
