### ISSUE TITLE
Sanity issues with Quark furniture

### ISSUE THREAD

**Issue by Agret-Brisignr** [LunaPixelStudios/Fear-Nightfall#17]
### Describe the Bug

When sitting on Quark furniture near campfires, sanity will not increase

### Reproduction Steps

1. Be within the sanity-affecting range of a campfire
2. Sit on a furniture from Quark within that range

### Screenshots and Videos

[Short clip of the issue](https://www.youtube.com/watch?v=_vuHIDL244o)]

Also note that my sanity is still affected by other sources, just not by the campfire. If I were hungry, it would go down. If I ate, It would go up, etc.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v6

### Other Mods

Added - ReAuth
Removed  - Server Browser

**Comment by SHXRKIIE** [comment]
Report to the dev
https://www.curseforge.com/minecraft/mc-mods/sanity-descent-into-madness
