### ISSUE TITLE
After update v7 not spawn anything evil mob expect herobrine mobs. In hard, normal etc not spawn.

### ISSUE THREAD

**Issue by Marwinkas** [LunaPixelStudios/Fear-Nightfall#18]
### Describe the Bug

After update v7 not spawn anything evil mob expect herobrine mobs. In hard, normal etc not spawn.

### Reproduction Steps

1. join world

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/87604769/2be89f1c-cbee-4925-b891-5457d7f5a9a0)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v7

**Comment by Marwinkas** [comment]
I created the world in a creative and also none of the evil mobs except Herobrine mobs. but after killing that's thing boss, everything spawn again, maybe the problem is in this mod abomination

**Comment by SHXRKIIE** [comment]
![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/79353591/0c429ed3-26ae-43bc-9a58-d6b1eff11c3c)
no issues here

**Comment by SHXRKIIE** [comment]
Ok i see now, will push out a HF
