### ISSUE TITLE
grass not loading correctly

### ISSUE THREAD

**Issue by DarkWolfxx** [LunaPixelStudios/Fear-Nightfall#2]
### Describe the Bug

I downloaded the modpack and created a world and my grass is invisible I have changed no settings and am having this issue I've tried changing a bunch of video settings to no fix.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-10-25_18 43 33](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/149022619/3ffddefe-749e-4c66-8b5d-984d84f09a06)

![2023-10-25_18 43 37](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/149022619/8544b3be-3e84-4852-9d4f-aa89820211cf)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

version 3

**Comment by SHXRKIIE** [comment]
Reinstall the modpack, also you were on a MP server?
