### ISSUE TITLE
UI mod causing issues with hopper

### ISSUE THREAD

**Issue by MojaveMarauder** [LunaPixelStudios/Fear-Nightfall#20]
### Describe the Bug

I'm trying to use hoppers under my bamboo spikes to gather loot and its not placing properly with the mod that adds the interactable ui so that you don't have to open menus (examples: furnaces, crafting tables, barrels, and hoppers) I just want to know what the mod is called so I can just personally remove it from my mods folder.

### Reproduction Steps

try placing a 2x3 rectangle of hoppers and get them to pipe into 1 chest

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8

### Other Mods

n/a

**Comment by SHXRKIIE** [comment]
immersive mc
