### ISSUE TITLE
New update making world generation slow

### ISSUE THREAD

**Issue by FryFish4U** [LunaPixelStudios/Fear-Nightfall#21]
### Describe the Bug

When exploring and generating new chunks in my world, minecraft will occasionally freeze for around 5 minutes. My FPS will stay at a capped 60 but blocks wont drop items and mobs will stand still and be unresponsive.

### Reproduction Steps

1.Explore new chunks
2.Try break some blocks when chunks doesn't generate
3.Wait until world catches up

### Crash Report or Log

https://gist.githubusercontent.com/FryFish4U/8ce4b2139ceb2e8daca726a0b96fed30/raw/c361bab0dc52ac49022cf1ad45422bae9810350f/gistfile1.txt

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v7.5

**Comment by FryFish4U** [comment]
Want to add that this wasnt an issue with v6 of the modpack

**Comment by SHXRKIIE** [comment]
Update to v8
