### ISSUE TITLE
Downloading through website and it have only 1 mod

### ISSUE THREAD

**Issue by SadlekAski** [LunaPixelStudios/Fear-Nightfall#24]
### Describe the Bug

well the title says all
Even loading every file in game will have 4 mods only (With optifine, without same problem)

### Reproduction Steps

1.Download from website (any version)
2.Open it and u have only 1 mod
3.In game its too only 1 mod
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/129619951/de21f118-736a-429d-ab7c-f7eb80bae9b9)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear+NightFall v8

**Comment by SHXRKIIE** [comment]
Use a modded launcher

**Comment by SadlekAski** [comment]
> Use a modded launcher

I did already but why it works like that

**Comment by Holero21** [comment]
Had the same problem, fix it by downloading the server installation file
