### ISSUE TITLE
Disappearing animals

### ISSUE THREAD

**Issue by Skibidypop** [LunaPixelStudios/Fear-Nightfall#28]
### Describe the Bug

Spawning animals disappear, when placing the animal with carryon or using eggs in creative, the animal has a chance to disappear. created a new instance with no added mods and a new world and it happened,

### Reproduction Steps

1.get animal egg / pick up animal with carryon
2.spawn bunch of animals / place animal
3. some will despawn / sometimes will disappear
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear nightfall v9

**Comment by SHXRKIIE** [comment]
update v10

**Comment by SkarletShadows** [comment]
I still have this issue in V10. animals disappearing with carryon when replaced
