### ISSUE TITLE
Biomancy 2 Mod Conflicts Prevent Pack Advancement

### ISSUE THREAD

**Issue by EntropyParadigm** [LunaPixelStudios/Fear-Nightfall#3]
### Describe the Bug

Bio-Forge Recipes cannot be displayed which prevents players from advancing to the End or past Chapter 3 of the quest line. 
NERB and the Recipe Essentials mod disable the recipe book which Biomancy uses for the Bio-Forge recipes.
Additional details can be found in the mod authors discord here: https://discord.com/channels/920005236645572662/1166953372205731880

As a workaround you can disable the two mods conflicting with Biomancy and use /recipe give "player name" *
This unlocks the recipes using the recipe book and allows the recipes in the Bio-Forge to display.

### Reproduction Steps

1. Open Bio-Forge, recipes are not displayed/empty.
2.
3.
...

### Screenshots and Videos

<img width="978" alt="Screenshot 2023-10-25 at 8 25 09 PM" src="https://github.com/LunaPixelStudios/Fear-Nightfall/assets/32775097/9b687a71-fdf3-47a8-924a-07bfde0a5187">

### Operating System

ANY

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v3

**Comment by SHXRKIIE** [comment]
Fixed in v4
