### ISSUE TITLE
Discord? / if not then a question

### ISSUE THREAD

**Issue by Daniellevi12** [LunaPixelStudios/Fear-Nightfall#34]
### Describe the Bug

first is there a Discord server for asking questions or something?
If not is there a way to get more mahogany wood (like in natural generation and not from quests)

### Reproduction Steps

1.  just a question
2.
3.
...

### Operating System

Windows 10 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

**Comment by SHXRKIIE** [comment]
Not sure how you can miss the discord button on the project page, in the modpack menu and in the game pause screen.
