### ISSUE TITLE
Phantom spawning enabled

### ISSUE THREAD

**Issue by jadonbp** [LunaPixelStudios/Fear-Nightfall#35]
### Describe the Bug

Title explains as much as is needed, phantoms still spawn every night.

### Reproduction Steps

N/A

### Screenshots and Videos

<img width="1710" alt="Screenshot 2023-11-27 at 7 51 18 PM" src="https://github.com/LunaPixelStudios/Fear-Nightfall/assets/87814794/555d778e-1953-4990-bbed-861f4b83049d">

### Operating System

MacOs

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v9-v10

**Comment by SHXRKIIE** [comment]
Wil ldisable next update
