### ISSUE TITLE
Fear Nightfall crashing on start

### ISSUE THREAD

**Issue by msjulyfive** [LunaPixelStudios/Fear-Nightfall#36]
### Describe the Bug

When I launch the game, I have a pop up message saying the game crashed with the Exit Code: 1. This is the crash report:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbe4293ca0, pid=26844, tid=21832
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x193ca0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://aka.ms/minecraftjavacrashes
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**The rest of the report is in the file below.**
[crash report.txt](https://github.com/LunaPixelStudios/Fear-Nightfall/files/13494701/crash.report.txt)

### Reproduction Steps

1. Download minecraft (vanilla)
2. Download curseforge
3. Download Fear Nightfall modpack
4. Launch the modpack via curseforge
5. Click play on the launcher (43.3.5)
6. The modpack will download in the launcher
7. The error message appears after a brief loading time

### Screenshots and Videos

N/A

### Crash Report or Log

I put a file in the description

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

### Other Mods

No.

**Comment by SHXRKIIE** [comment]
Driver issue

**Comment by msjulyfive** [comment]
My drivers are up to date (GeForce version 546.17) and the same crash occurs with the same exit code, could there be another issue?

**Comment by PissMaster45** [comment]
I also have this issue and updated my drivers yesterday with GeForce version 546.33 as of 12/12/2023. I am also getting the Exit Code 1 message.

**Comment by PissMaster45** [comment]
![image_2023-12-12_194442296](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/153571786/6e322219-0061-4321-824e-f4b5208d1553)
