### ISSUE TITLE
 Hide duplication

### ISSUE THREAD

**Issue by Axyl69** [LunaPixelStudios/Fear-Nightfall#4]
### Describe the Bug

If you shift+rmb a tanner with hide in it it picks up the tanner but drops hide. You can replace the tanner (that still has hide in it) and infinitely do this.

### Reproduction Steps

1. Place Leather Tanner from ButchersDelight
2. Place Raw Hide in Tanner
3. Shift+RMB Tanner to pick up
4. Place tanner
5. Repeat 3-4

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v3

**Comment by SHXRKIIE** [comment]
Fixed in v4
