### ISSUE TITLE
Mobs disappearing

### ISSUE THREAD

**Issue by BlairOswin** [LunaPixelStudios/Fear-Nightfall#43]
### Describe the Bug

I do not know if this is a feature or a bug but throughout my playthrough my animal mobs have been disappearing. I've had cows vanish from my base while I'm off on adventures and even a cured villager disappeared from a safe area in my cave base.

The instance I recorded evidence from was breeding.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

https://imgur.com/a/htGkKsx

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V10

**Comment by Inteprise** [comment]
incontrol config has a set limit of 5 mobs 

        "dimension": "minecraft:overworld",
        "mod": "endofherobrine",
        "mincount": 5,
        "result": "deny"

because of this any new possessed mobs seem to be yeeted from the world

**Comment by SHXRKIIE** [comment]
> incontrol config has a set limit of 5 mobs
> 
> ```
>     "dimension": "minecraft:overworld",
>     "mod": "endofherobrine",
>     "mincount": 5,
>     "result": "deny"
> ```
> 
> because of this any new possessed mobs seem to be yeeted from the world

It is not this, is because we blacklisted Pigs, sheep and some other herobrine mobs because people complain about them, so its just herobrine mobs being removed not that there are an issue

**Comment by SkarletShadows** [comment]
> > incontrol config has a set limit of 5 mobs
> > ```
> >     "dimension": "minecraft:overworld",
> >     "mod": "endofherobrine",
> >     "mincount": 5,
> >     "result": "deny"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because of this any new possessed mobs seem to be yeeted from the world
> 
> It is not this, is because we blacklisted Pigs, sheep and some other herobrine mobs because people complain about them, so its just herobrine mobs being removed not that there are an issue

Wait so are farm mobs supposed to be vanishing? I keep collecting them and they vanish over time?
