### ISSUE TITLE
NBT Load Error Resulting in Disconnect within a Chunk

### ISSUE THREAD

**Issue by TamashiNoShi** [LunaPixelStudios/Fear-Nightfall#45]
### Describe the Bug

Issue: When players walk or move into this specified area around the cords [-818 110 -5582]  the disconnect with the error listed in the attached image. When i player rejoins they will disconnect immediately with the same error message. 

### Reproduction Steps

1. Move Player in the area listed in the issue
2.
3.
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Fear-Nightfall/assets/44934910/7e25d08d-1ad9-41c9-b4cc-6280e0e6a125

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

### Other Mods

[server243305_6_Dec_2023_22_2_49.zip](https://github.com/LunaPixelStudios/Fear-Nightfall/files/13594843/server243305_6_Dec_2023_22_2_49.zip)
[latest.zip](https://github.com/LunaPixelStudios/Fear-Nightfall/files/13594844/latest.zip)

**Comment by TamashiNoShi** [comment]
If you want access to all server files please ask. I will GLADLY give you perms to the Bisect server as a User

**Comment by SHXRKIIE** [comment]
Update to v11, if that doesnt fix it see if removing the XL Packets mod and replacing it with Packer Fixer mod fixes it

**Comment by TamashiNoShi** [comment]
Both recommendations did not fix the issue.

**Comment by TamashiNoShi** [comment]
God damn i'm fucking stupid. It's fixed...Didn't download the correct version of Packet Fixer
