### ISSUE TITLE
carryon bugs and passive mobs disappearing

### ISSUE THREAD

**Issue by SkarletShadows** [LunaPixelStudios/Fear-Nightfall#46]
### Describe the Bug

- Placing mobs, maybe just passive mobs, makes them disappear using carryon. I have clips of this happening.
- Passive mobs disappear randomly when left in pens.
- mini map spazzes out when carrying things

### Reproduction Steps

1. pick a mob up
2. place the mob
3. mob disappears sometimes if not often.
...

### Screenshots and Videos

https://outplayed.tv/media/RXjoX2

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V10

**Comment by SHXRKIIE** [comment]
Update to latest
