### ISSUE TITLE
You are breaking the CurseForge Terms of Service

### ISSUE THREAD

**Issue by RPMYT** [LunaPixelStudios/Fear-Nightfall#47]
### Describe the Bug

Hi, as I'm sure you're aware your library mod 'Teraphobia' contains deliberate crash code if Essential is found.
Additionally, while you probably already know this, this violates the CurseForge Terms of Service.
It would be wise to remove the offending code swiftly; lest you incur repercussions.
That is all. Have a nice day.

### Operating System

N/A

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

N/A

**Comment by SHXRKIIE** [comment]
Talked to CF, not breaking any TOS but will remove it anyways and the mod is still incompatible as we already have a mod that provides free hosting.
![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/79353591/de41b183-f377-446b-86d3-f7a2531fcaf4)
