### ISSUE TITLE
Game crashes upon start

### ISSUE THREAD

**Issue by 20BUCKZ** [LunaPixelStudios/Fear-Nightfall#48]
### Describe the Bug

me and a few buddies wanted to play this modpack but only half of us could even get it to load, its hard to explain because the guys who managed to do it couldn't figure out why it even worked for them

### Reproduction Steps

1. Download Minecraft Java
2. Download CursedForge
3. Download Fear Nightfall V11.5 Modpack through CursedForge
4. Run Fear Nightfall V11.5 with cursedforge modloader version 43.3.5 on minecraft launcher
5. Click play with forge-43.3.5 selected
6. Mod begins loading
7. Game crash error pops up after brief moment

### Crash Report or Log

https://pastebin.com/G2eCgPRN

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V11.5

### Other Mods

no other mods

**Comment by SHXRKIIE** [comment]
Update your drivers
