### ISSUE TITLE
Too Many Creepers

### ISSUE THREAD

**Issue by Gurkk80** [LunaPixelStudios/Fear-Nightfall#49]
### Describe the Bug

I recently started my first two playthroughs and each time a creeper ended my run. Each night I usually find 4-5 creepers every time a wave of enemies shows up. This normally wouldn't be an issue, but the creepers can be triggered far more easily than normal creepers. I tested this out in creative and I was just standing and I could hear footsteps outside, and then all of a sudden one of them blows up. No trigger, no nothing. This means that the only feasible bases one could build would be out of cobble. Even underground bases fall, victim since they'll just come up to your door and blow it up. This makes having a permanent base near impossible and is extremely annoying. I understand if this is intentional behavior but considering the sheer amount of creepers that spawn I don't know if it is. In a single night, I had 9 creepers come up to my base and blow up, all in a single night which destroyed the base I had worked on for the entire day. I even tried hiding in the base and not doing anything, and still, the original issue arose where they just randomly blew up. I'd understand this behavior on hard difficult or hardcore, but I was on easy, and still, this was happening.

### Reproduction Steps

(This is for the random creeper detonations)
1. Construct Base
2. Sit in base and wait
3. Eventually a creeper will come up and randomly start hissing and blow up

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11.5

**Comment by SHXRKIIE** [comment]
The ai are meant to be like that regardless of the difficulty because this whole modpack is hard, a lot of people either complain there is too much and then too little, its all about biomes and strategies. If you dont like it disable creepers in enhanced ai.
