### ISSUE TITLE
Herobrine signs display enum/key instead of value

### ISSUE THREAD

**Issue by Hunter24681** [LunaPixelStudios/Fear-Nightfall#50]
Describe the Bug
Signs placed by herobrine show what looks like a message key instead of the intended message

Reproduction Steps
Run minecraft fear nightfall v11.5
Wait for herobrine to place a sign (not sure if there's a command to speed this up)
Sign will appear incorrectly

Screenshots and Videos
![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/76822995/51c65728-91ba-4bad-889d-125916af69a1)

Operating System
Windows 10

Minecraft Version
1.19

Modloader
Forge w/ ATLauncher

Modpack Version
V11.5

Other Mods
no other mods

**Comment by chorbintime** [comment]
is this issue persistent in the latest version of the modpack?

**Comment by Hunter24681** [comment]
I haven't touched the pack in a while.  It was there in 11.5, but I see you've upgraded to 12.  I may be able to go back in and check in the near future, but otherwise if there wasn't a fix for this implemented in version 12 I would assume it's still there.

I'm not sure if there's a way to force the sign event?  If so it would be easy for me to check.  Otherwise it may take a while waiting

**Comment by Cooliosity** [comment]
the issue is persistent in the latest version of the modpack

**Comment by chorbintime** [comment]
will look into it for next update
