### ISSUE TITLE
No sound in modpack through headphones

### ISSUE THREAD

**Issue by ForgedImmortal** [LunaPixelStudios/Fear-Nightfall#51]
From button clicks to blocks and mobs, the Fear Nightfall modpack downloaded through curse forge has 0 volume output for me through headphones. Launching vanilla versions, other modpacks, etc the sound is fine, so I am only left wondering if its something in the pack.
I apologize if this issue doesn't belong here, but I can't seem to find a fix anywhere online, and have tried everything I can think of from reloading sounds, restarting pc, redownloading modpack and backups, and checking audio devices.

**Comment by SHXRKIIE** [comment]
Please report with our template
