### ISSUE TITLE
Fear Nightfall crashing on start

### ISSUE THREAD

**Issue by PissMaster45** [LunaPixelStudios/Fear-Nightfall#52]
### Describe the Bug

When I launch the game, I have a pop up message saying the game crashed with the Exit Code: 1. This is after downloading and installing GeForce version 546.33 as of 12/12/2023.

### Reproduction Steps

1.Download minecraft (vanilla)

2.Download curseforge

3.Download Fear Nightfall modpack

4.Launch the modpack via curseforge

5.Click play on the launcher (43.3.5)

6.The modpack will download in the launcher

7.The error message appears after a brief loading time

### Screenshots and Videos

![Screenshot 2023-12-12 194437](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/153571786/9a03c01a-acb1-4683-91e2-bd92178d8bea)

### Crash Report or Log

https://pastebin.com/3RESfq1F

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11.5

**Comment by SHXRKIIE** [comment]
Update drivers

**Comment by PissMaster45** [comment]
Updated driver and the issue persists. Uninstalled Minecraft and Forge. Reinstalled Minecraft and Forge. I do not have this issue playing other modpacks made by other creators.

**Comment by FoolishGrackle** [comment]
Make sure you have ALL drivers updated this includes all AMD and NVIDIA drivers if you have both brands
