### ISSUE TITLE
Leg Spike can't be picked up

### ISSUE THREAD

**Issue by TGee001** [LunaPixelStudios/Fear-Nightfall#53]
I had managed to kill a monster and he dropped something called a leg spike but for some reason, I can't pick it up. Am I missing something? 
![2023-12-14_13 57 58](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/135569814/2f609abf-4e32-4eac-a79a-8529f6313b5d)

**Comment by SHXRKIIE** [comment]
its been disabled and removed if oyu are on latest
