### ISSUE TITLE
Game crashes when pressed play 

### ISSUE THREAD

**Issue by Oinkcelot4** [LunaPixelStudios/Fear-Nightfall#54]
### Describe the Bug

Hello, so whenever my friend tries to play Fear Nightfall, her game crashes and gives her Exit Code 1. Now we did try to update her drivers to the latest version ( RTX 3060 Laptop) which was driver version 546.33. That was released back in the 12th of December though. We have also tried updating Java, reinstalling Java, reinstalling Cursed Forge and the Nvidia drivers yet the issue still persists. Right now, she is playing HorrorCraft and that one Mustard Zombie Gas modpack or whatever and faces no issues. Would you guys might have any idea of what to do? I'm out of ideas and I'm just waiting for the next nvidia driver update to come by so I can install it for her. 
Sorry and Thanks. 

### Reproduction Steps

1.  Press play on Curse Forge 
2. Press play on launcher 
3. Game crashes
...

### Screenshots and Videos

![image_2024-01-07_164423666](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/155921123/014eafae-cbfd-4632-b93f-abb0c59d7a34)

### Crash Report or Log

https://pastebin.com/j2qLR4vS

### Operating System

WIndows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

11.5 HF

### Other Mods

None

**Comment by SHXRKIEgg** [comment]
Update drivers

**Comment by maxratx** [comment]
i hacve solved it freind!! create a copy of the modpack profile and go in profile propertys and enable modifications to it and then go into the mod pack and click disable on vr related mods or mods that look like they would crash a normal computer idk but it works!!🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️🕷️

**Comment by maxratx** [comment]
nvm it crushs on world gen now but im gonna keep trying
