### ISSUE TITLE
voice chat not working and showing plug in bottom left.

### ISSUE THREAD

**Issue by Craze5236** [LunaPixelStudios/Fear-Nightfall#57]
### Describe the Bug

Occasionally get a bug were the voice chat doesn't function whatsoever and then displays a power plug in bottom left. No other mods installed.

### Reproduction Steps

1.Just load up current version of fear nightfall.
2.get in multiplayer server
3.enable voice chat
4.try to voice chat and it might have the plug icon pop up.( random sometimes).

### Screenshots and Videos

![2024-01-14_16 45 17](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/156623622/db5dfc1c-64d3-4ef1-81c0-436c7b91845d)

### Crash Report or Log

N/a no crash

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

11.5 HF

### Other Mods

NONE

**Comment by SHXRKIEgg** [comment]
You need to set it up
