### ISSUE TITLE
Cant Sleep

### ISSUE THREAD

**Issue by MrsJessy92** [LunaPixelStudios/Fear-Nightfall#58]
### Describe the Bug

when i try to slepp (at night of course) then its not happening.. it always says it has to be night to sleep... but it is night... i made more worlds to see if there is a problem with the world but its always happening :/

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-01-23_19 42 23](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/157525995/e37cc887-3828-4a7e-9358-7572877984b5)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11.5HF

**Comment by SHXRKIEgg** [comment]
if you read the quests you cant sleep
