### ISSUE TITLE
Tenebrous lands mobs not spawning from mobspawners

### ISSUE THREAD

**Issue by Prim4ry01** [LunaPixelStudios/Fear-Nightfall#59]
### Describe the Bug

I found a spawner with one of the tenebrous lands mobs in it. Unfortunately, no mobs spawn from the spawner at all. I swapped the spawner to a vanilla mob (skeleton) and it worked immediately, but when I swapped it back it stopped working again.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
report it to the developers of the tenebrous lands mod
