### ISSUE TITLE
Server Crashes when Siren Head spawns in.

### ISSUE THREAD

**Issue by ZSALUS** [LunaPixelStudios/Fear-Nightfall#6]
### Describe the Bug

I'm hosting a non-dedicated server, Im in a old_growth_pine_taiga biome at night, when siren head spawn in it takes usualy 1 minute and the server disconnects you with "**_Timed out"_**. Tried to be in the same forrest with peaceful mode and everything worked well but after chanching back the difficulty to normal and siren head spawned in, the server disconnects you. The server just stops no reaction for commands in console and it doesn't leave a crash log in the files.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V4.5

**Comment by SHXRKIIE** [comment]
Remove his spawn via Teraphobia config, add its id in there, should be like boh:siren_head

**Comment by moriful** [comment]
> Remove his spawn via Teraphobia config, add its id in there, should be like boh:siren_head

how do i do that
