### ISSUE TITLE
Spore mobs are not attacking normal mobs

### ISSUE THREAD

**Issue by TioJobso** [LunaPixelStudios/Fear-Nightfall#60]
### Describe the Bug

The Spore monsters just don´t attack the ordinary mobs(like zombies, villagers etc), and that´s really important for their evolution as well, instead of that, they just choose to kill the player

![2024-01-26_03 06 30](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/92833698/ebee12a2-d246-40dc-a511-6340e7f0743e)

As you can see in the image, the "Infected human", ignores completely the villagers

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear NightFall v12

**Comment by SHXRKIEgg** [comment]
Delete the config

**Comment by TioJobso** [comment]
> Delete the config

how can I do that?
