### ISSUE TITLE
Fear Nightfall Exit Code 1

### ISSUE THREAD

**Issue by Uuzio** [LunaPixelStudios/Fear-Nightfall#62]
### Describe the Bug

When launching Fear Nightfall through Minecraft launcher, an error message appears. The error message is Exit Code 1.

### Reproduction Steps

1.  Press play on Cursed Forge
2. Press play on Minecraft launcher
3. Error message appears; Exit Code 1
...

### Screenshots and Videos

![Screenshot 2024-01-27 022541](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/157884146/5ce95a36-d0aa-46d8-b3c1-d777262e4f54)

### Crash Report or Log

https://gist.github.com/Uuzio/89f8855299480130a0be5a33ffc8ed00

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by Uuzio** [comment]
Geforce Game Ready Driver is updated to Version: 551.23 as of 1/27/2024
Minecraft Java Edition: 1.20.4 
Java: JDK 21

**Comment by Uuzio** [comment]
https://gist.github.com/Uuzio/dbd21af2358194c4e3879d05de075f0c 
If this helps, this is the Minecraft game output . Please help if possible.

**Comment by SulfuricCrowd3** [comment]
So... Was you able to solve it?
