### ISSUE TITLE
Server crash when going to the Aether

### ISSUE THREAD

**Issue by apuerto11** [LunaPixelStudios/Fear-Nightfall#63]
### Describe the Bug

As soon as I loaded in the Aether the server crashed. Everytime the server is restarted and I reconnect it crashes.

### Crash Report or Log

https://pastebin.com/zpfmmx8J

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11.5 HF

**Comment by SHXRKIEgg** [comment]
You modified the modpack, thats why its crashing
