### ISSUE TITLE
Can´t Connect Chest and Hoppers to each other while Crounching

### ISSUE THREAD

**Issue by Nilsbrb** [LunaPixelStudios/Fear-Nightfall#65]
### Describe the Bug

As the Title says i cannot place chest together to form the bnig Chests and i cannot connect Hoppers to each other or to Chests even tho i am crounching and i dont know why because it worked in the beginning of playing fear nightfall and now i cannot do it.
I didn´t change any Settings or other stuff so i cannot explain the Bug.
Please Help!

Much Love

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10 Home

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11.5 HF

**Comment by chorbintime** [comment]
Can you record a video of the issue?

**Comment by Twumain** [comment]
Had the same problem, just open the ImmersiveMC Settings. The default keybind is comma. And go to customize immersives and scroll down-ish to Bypass Immersion While Crouching and set it to off. It was driving me and friend bonkers. Hope this helps.
