### ISSUE TITLE
End keeps lagging(a lot)

### ISSUE THREAD

**Issue by carlosgoldfreefire** [LunaPixelStudios/Fear-Nightfall#66]
### Describe the Bug

When I am in survival and look up in the end dimension, I suddenly hit 0 fps, even while looking at nothing.

### Reproduction Steps

1. Go to the end
2. Look up

### Screenshots and Videos

https://github.com/LunaPixelStudios/Fear-Nightfall/assets/158296811/50af290c-8f41-49a8-b3bb-5cddbdbcc543

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by carlosgoldfreefire** [comment]
This also happens in the nether roof

**Comment by carlosgoldfreefire** [comment]
And also in the aether

**Comment by SHXRKIEgg** [comment]
Whats your pc specs and how much ram allocated?

**Comment by carlosgoldfreefire** [comment]
I have a GTX 1650 and a i7 7700, and I use my system memory settings (I have 8GB of ram)

**Comment by chorbintime** [comment]
please run a spark profiler with /sparkc profiler start and then send the link here after running the stop command

**Comment by carlosgoldfreefire** [comment]
nvm I reinstalled the modpack and it started working again, don't know why
