### ISSUE TITLE
Smithing Table UI

### ISSUE THREAD

**Issue by MikeTah** [LunaPixelStudios/Fear-Nightfall#67]
### Describe the Bug

Smithing table has new visuals, but old usage. I was messing around in creative mode and backpacks when I noticed it. The mouse location is between the upgrade location and the finished product location.

### Reproduction Steps

1. place down a smithing table
2. move cursor over the ui
3. notice that the ui does not match visuals
...

### Screenshots and Videos

![2024-02-03_11 38 41](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/158774109/a2ad37a9-633e-4bbd-82e9-35af06b40f7a)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
will be fixed in the next update
