### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by toonnongaeoy** [LunaPixelStudios/Fear-Nightfall#68]
The mod can't launch due to "The paging file is too small for this operation to complete."

How to reproduce.
Launch the game with a maximum of 14000 MiB RAM allocation on Prism Launcher.

Error log output
[Other logs.](https://mclo.gs/oYI8Nl6)
[MC Logs.](https://mclo.gs/ZUGXsjj)

Spec :
Intel Core i5-11400H
NVIDIA GeForce RTX 3050 Laptop GPU
16GB RAM 
Windows 11

**Comment by toonnongaeoy** [comment]
But surprisingly, it works on same machine but in Linux.
![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/82090464/bc5db95f-2238-44c8-9a3a-a5ad21ae6e0d)

**Comment by SHXRKIEgg** [comment]
You cant allocated 14gb of memory when your whole pc has 16gb, allocate 8 gb

**Comment by toonnongaeoy** [comment]
Even I set my ram back to 8GB, still the same on Windows 11

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/82090464/21062472-1037-4cbb-9e1a-4f121a2690cf)

And in Linux, I only allocated ram only 8GB and it works perfectly fine.

**Comment by toonnongaeoy** [comment]
Here's the log. https://mclo.gs/PpaHQl1
