### ISSUE TITLE
Problem with block indicaor

### ISSUE THREAD

**Issue by ProcMSK** [LunaPixelStudios/Fear-Nightfall#69]
### Describe the Bug

When i started playing minecraft mod "Fear Nightfall" , i had some frame in left top corner that was showing me whatam i looking at (mobs, creatures, blocks... everything). but somehow it disappeared and now i cant get it back. I dont know how it dissapeared , or did i just randomly turned it off. i Dont know. I need help please

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v12

**Comment by SHXRKIEgg** [comment]
in game > esc > mods > jade > enable in config
