### ISSUE TITLE
"NBT tag that was too big" leading to client disconnecting.

### ISSUE THREAD

**Issue by kz2wd** [LunaPixelStudios/Fear-Nightfall#7]
### Describe the Bug

"Internal Exception: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097156bytes where max allowed: 2097152"

### Reproduction Steps

Unfortunatly, I have no idea for how to reproduce the bug.

It appears when a player is loading our base, and will kick the player within 2~3 seconds.

The log contains a lot of lines like this :
[01:25:16] [Render thread/WARN]: Reclaimed 48960 bytes at address 2153133641152 that were leaked from an unknown location (logging is disabled)

Maybe it could be that a block causes a memory leak client side ?

I am sorry as I have no further information on the subject, 

The log is client side.

### Crash Report or Log

https://pastebin.com/h5PDxcib

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v4.5

**Comment by SHXRKIIE** [comment]
can you see if removing voicechat client and server side works? also update to v5

**Comment by kz2wd** [comment]
I found a workaround using this : https://modrinth.com/mod/create-big-contraptions/version/1.0
It seems that increasing the limit is enough, however it is weird that we required it, considering we only did a bit of immersive and act I.

**Comment by SHXRKIIE** [comment]
How is this server hosted and is it online mode?

**Comment by kz2wd** [comment]
I am hosting it on a PC with ubuntu 22.04. Online mode is set to true, I didn't change much in the settings.

**Comment by SHXRKIIE** [comment]
Could you send the server log, we have XL Packets so this shouldnt happen
