### ISSUE TITLE
Frozen Loading Screen

### ISSUE THREAD

**Issue by LetaStar** [LunaPixelStudios/Fear-Nightfall#70]
### Describe the Bug

Loading screen when joining a game will not go away, but I can still play the game as if it's not there. I assume this is a visual bug

One thing to note, in the latest log there is a LOT, and I mean a LOT of errors that are the same, and it seems they were uploading every millisecond,,,

### Reproduction Steps

1. Install mod pack 
2. Join a world
3. Loading screen appears
4. The loading screen stays stuck, but I can move around and hear things normally

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/69783691/35369afb-8ebe-424b-9de0-d9c239d8f859)

### Crash Report or Log

[latest.log](https://github.com/LunaPixelStudios/Fear-Nightfall/files/14291024/latest.log)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Other Mods

no other mods

**Comment by chorbintime** [comment]
What launcher did you install the modpack on clientside?

Are you joining a server? If so, how was it installed?

**Comment by chorbintime** [comment]
Its an Aternos issue. You're better off hosting your own server for free with the serverpack, because Aternos hardware cant handle modpacks.
