### ISSUE TITLE
Windows 11 Blue Screen

### ISSUE THREAD

**Issue by neoisntavailable** [LunaPixelStudios/Fear-Nightfall#71]
### Describe the Bug

Windows 11 crashes upon opening up Fear Nightfall, not sure if it only happens on ATLauncher since that is what I use but it will spit out a System Service Expectation error everytime. I had scanned all of my drives and no errors were found within them and only crashes with Fear Nightfall and not any other modpack.

### Reproduction Steps

1. Use ATLauncher, download Fear Nightfall as instance.
2. Open it.
3. Wait for it to crash.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v12

**Comment by SHXRKIEgg** [comment]
If it is blue screening, thats not the modpack, thats something to do with your pc
