### ISSUE TITLE
Mod crashing and not preparing to open up at all.

### ISSUE THREAD

**Issue by Svmnu** [LunaPixelStudios/Fear-Nightfall#72]
### Describe the Bug

At first when loading the mod through java there was an error code 6 that popped up. I updated my java to the latest edition and now it was even prepare the mod at all it starts slightly then closes out the entire Minecraft launcher. Is there a way to fix this? I have been playing it on my Mac, so I am just lost on why it isn't working anymore.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

error code 6

### Operating System

Mac

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by SHXRKIEgg** [comment]
Need crash/log
