### ISSUE TITLE
how to get to heaven

### ISSUE THREAD

**Issue by Mqvxm** [LunaPixelStudios/Fear-Nightfall#73]
### Describe the Bug

To get to heaven, you need to kill herobrine, but to get to it you need to kill 13 mobs, how to kill them if they are on the ban list
You can't go to heaven while Herobrine is alive

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

**Comment by nvb-uy** [comment]
You have to complete the previous campaign chapters. Herobrine is the last chapter.

The Aether is unlocked after you defeat the ender dragon
