### ISSUE TITLE
Title screen menu on ingame hud

### ISSUE THREAD

**Issue by CrvckHeadEnergy** [LunaPixelStudios/Fear-Nightfall#74]
### Describe the Bug

hello
í installed essentials (i know i schouldnt but it works) cause we dont want du buy a server just for playing as 3 people and they are to laggy, but sometimes there is this bug and i dont know how to get rid of it it just desappears after doing some repair and sometimes it just wont please help

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/161589549/a151a263-bcdc-4659-9713-5b3986d337f3)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

43.3.5.  1.19.2

### Other Mods

Essentials

**Comment by chorbintime** [comment]
Essential is incompatible and causes world corruption. The modpack already comes with world hosting in the ingame pause menu.

**Comment by Lamizor** [comment]
disabling and re enabling shaders fixes it :)
