### ISSUE TITLE
Mismatched Mods

### ISSUE THREAD

**Issue by RyzeXS** [LunaPixelStudios/Fear-Nightfall#75]
### Describe the Bug

Mismatched mods called fear the dark, but theres no mods that called fear the dark

### Reproduction Steps

I use no mods for my client, and then i starts to play the modpack from a server, but as usually theres a mismatched mods because i have no mods from my client, and i started to add the mods from the mismatched list, until theres only 1 mod that is called fear the dark, and i look that mod names in modpack, and i found nothing. But if i installed all the mods from modpack to my client, it works with no problems, i want to install the minimal amount of mods installed to my client for better performance, and because of that. Does someone knows about whats the problem with the mismatched mods called "Fear The Dark"

### Screenshots and Videos

![image-1](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/162409563/101178c1-3ad6-4372-9fe5-dda2bf414cc1)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V12

**Comment by chorbintime** [comment]
you didnt install the modpack correctly client or server side. this isn't an issue with the modpack itself.
