### ISSUE TITLE
Hi! I hav a small problem.

### ISSUE THREAD

**Issue by VoldemarCHERT** [LunaPixelStudios/Fear-Nightfall#78]
### Describe the Bug

When i connect to local server of my friend his server gives an error message about 'an error occured in Luna'. We tried all the ways, but it didnt help. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
please send your latest.log file, or you can just host a server using the serverpack we provide on the modpack page.
