### ISSUE TITLE
Crash when placing candles with power effect (from hexerei) 

### ISSUE THREAD

**Issue by KeyDdd** [LunaPixelStudios/Fear-Nightfall#79]
### Describe the Bug

Crash when placing candles with power effect
mb its conflicting with taro card mod

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
please provide a crash report or a latest.log file
