### ISSUE TITLE
herobrine husk

### ISSUE THREAD

**Issue by Smewhey** [LunaPixelStudios/Fear-Nightfall#8]
### Describe the Bug

Herobrine spawns a husk and it cant be killed or moved far too often (8 times within 5 minuets)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V5

**Comment by SHXRKIIE** [comment]
Fixed
