### ISSUE TITLE
Carzy mob spawn in Woodland Manisons

### ISSUE THREAD

**Issue by ILikePzzaRolls** [LunaPixelStudios/Fear-Nightfall#81]
### Describe the Bug

Playing the latest release of this modpack and everytime i go to any woodland mansion there's a crazy amount of mobs there, like an unplayable amount. Even after modifying the incontrol config file there's no change.
Also even if i try to kill them more of them spawn so fast i can't keep up. 

### Reproduction Steps

1. go to any woodland mansion late game (if that madders) 

### Screenshots and Videos

Sorry for only screenshots dont have a recording software
![Skärmbild 2024-03-14 154410](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/94855080/427139c2-cafa-4bf6-8a1f-514869833a7f)
![Skärmbild 2024-03-14 154942](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/94855080/78ce3ea9-7f4c-4db7-b8f7-56acc6192031)
![Skärmbild 2024-03-14 154425](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/94855080/d064988b-3392-4cbc-9d2f-6e4c5f4356d0)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Other Mods

Haven't added any outer mods.

**Comment by chorbintime** [comment]
Are all of the mobs spawning from the same mod? What mobs are these?
