### ISSUE TITLE
Lag and Teleportation Issues with Sanity Mod on Multiplayer Server

### ISSUE THREAD

**Issue by JDTHEPS** [LunaPixelStudios/Fear-Nightfall#82]
### Describe the Bug

Severe lag occurs on a multiplayer server (8-12 players) when a player has low sanity and monsters spawn from the Sanity mod.
Lag manifests as:
    Delayed actions (around 2 seconds)
    Monster teleportation
    Player teleportation (every 2-5 seconds)

Despite server TPS being between 17.4-20, CPU load under 20%, and 9GB of RAM usage, the lag persists.

_*Additionally, the Map Atlases minimap fails to generate new regions, appearing blank. Updating the mod to the latest version resolved the minimap issue._

### Reproduction Steps

1.Join a multiplayer server with 8-12 players
2.Have one or more players lower their sanity in-game
3.Observe the server lagging significantly as monsters spawn from the Sanity mod.
4.Witness delayed actions, monster teleportation, and player teleportation.

### Screenshots and Videos

https://streamable.com/jjjvcu

### Crash Report or Log

No crash or error found on console

### Operating System

Ubuntu 22.04.3 LTS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall V12

### Other Mods

-

**Comment by JDTHEPS** [comment]
Also what mods that show block information when pointing at? I want to config the position

**Comment by chorbintime** [comment]
1. Can you run a spark profiler with /spark profiler start, and run the stop command after recreating the laggy behavior? Upload it here as the .sparkprofile file, you can download it from the link generated I'm pretty sure. 

The mod that displays block info is Jade

**Comment by JDTHEPS** [comment]
Sorry I can't find download button
In this test I only able to have 4 players to test but its enough to make server lag
Here is screenshot I think I have captured everything that should be need for analysis 

[ ( https://gofile.io/d/hOp1XN ) ]

**Comment by chorbintime** [comment]
Does removing Enhanced AI help?

**Comment by JDTHEPS** [comment]
It has improved; it has reduced server latency by half, and map generation is now faster.

**Comment by JDTHEPS** [comment]
but still have problem with delayed actions, monster teleportation, and player teleportation

**Comment by chorbintime** [comment]
Can you send a new spark profiler?
