### ISSUE TITLE
FPS is low

### ISSUE THREAD

**Issue by emilibibic** [LunaPixelStudios/Fear-Nightfall#83]
### Describe the Bug

FPS is between 7 - 16(at best)
-tried all settings available in Minecraft Video Settings, doesn't change performance.
version 11.5

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![mcfps](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/163609699/dc8d24b4-c4d4-45b3-88e3-41675b323b7f)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

FearNightfall

**Comment by chorbintime** [comment]
click the performance guide button on the main menu and follow the guide
