### ISSUE TITLE
Error Creating New Server (CurseForge)

### ISSUE THREAD

**Issue by AbaddonAbatu** [LunaPixelStudios/Fear-Nightfall#86]
### Describe the Bug

I downloaded the server pack from Curse Forge and ran the start.ps1 and I get the following error:

Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <:> at index 70: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar

I tried redownloading multiple times, I also tried running start.sh instead but came to the same outcome

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v12

**Comment by chorbintime** [comment]
please send the log file instead of just a snippet
