### ISSUE TITLE
Game crashing before even reaching minecraft home screen. 

### ISSUE THREAD

**Issue by ShaggerJ** [LunaPixelStudios/Fear-Nightfall#87]
### Describe the Bug

When loading up the game from the launcher, the game loads but crashes before reaching the home screen.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[hs_err_pid89556.pdf](https://github.com/LunaPixelStudios/Fear-Nightfall/files/14737172/hs_err_pid89556.pdf)

### Operating System

Sonoma 14.4 (Mac)

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Version 12

**Comment by kurisubrooks** [comment]
There is an issue with Java 17.0.8 and newer where you may experience "A fatal error has been detected by the Java Runtime Environment", which can cause the Java runtime to crash under a variety of circumstances. To resolve this:
1. Install the Zulu JDK 17.0.1+12 arm64 build of Java:
Direct download: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=7eb8ee44-ab7f-4afb-9e42-32bd76416400 
2. Download/Install ATLauncher or Prism Launcher (CurseForge Launcher is known to cause issues)
3. In Instance settings > Java, manually specify the following Java path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
4. If using ATLauncher, Disable "Use Minecraft-bundled JDK"
5. Launch the game
