### ISSUE TITLE
Extremely slow chunk Generation

### ISSUE THREAD

**Issue by ExpertyGames** [LunaPixelStudios/Fear-Nightfall#88]
It's impossible to explore, every time I try new chunks take a long time to load, I've even tried hosting my world or other worlds and nothing changes

Fear Nightfall v12

**Comment by chorbintime** [comment]
please run a spark profiler, /spark profiler start, then run the stop command after 5ish mins and send the link here

**Comment by ExpertyGames** [comment]
> please run a spark profiler, /spark profiler start, then run the stop command after 5ish mins and send the link here

there https://spark.lucko.me/Gw9i8vjdK4

**Comment by chorbintime** [comment]
You have a lot of programs open in the background. Your system CPU & memory usage is almost completely maxxed out. I would suggest closing background programs.
