### ISSUE TITLE
Lan multiplayer not working

### ISSUE THREAD

**Issue by hostag8756** [LunaPixelStudios/Fear-Nightfall#89]
### Describe the Bug

from what i think i understand the lan multiplayer can be used for online multiplayer with friends, problem is is that whenever anyone in our group of 3 tries to connect to any one of our worlds if give us the message "connection refused: no further information", and we dont know how to bypass this all of us have even deleted and redownloaded the modpack and no success 

### Reproduction Steps

1.person hosting opens lan and gives lunapixel link to others
2.others connect to lunapixle link via multiplayer tab
3.prompted connect refused: no furtherinformation
![fear refused](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/164843486/b122d133-4c04-47a6-a7b0-a41609501c4c)

...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Other Mods

no

**Comment by chorbintime** [comment]
do they have Fear Nightfall installed? if so, with what launcher?

**Comment by hostag8756** [comment]
we are all using curseforge

**Comment by chorbintime** [comment]
Retry on ATLauncher. If the issue persists, just use the serverpack on the modpack's curseforge page and follow the directions in the readme
