### ISSUE TITLE
Mixin Error Report

### ISSUE THREAD

**Issue by ZeroZonta** [LunaPixelStudios/Fear-Nightfall#9]
### Describe the Bug

Every time i attempt to start the game i get a mix in error and a few others

### Crash Report or Log

https://paste.atlauncher.com/view/b5ce4612-d181-4de1-a517-4043995bd41e

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear NightFall v5

### Other Mods

No

**Comment by SHXRKIIE** [comment]
Driver issue please update your driver from their website

**Comment by ZeroZonta** [comment]
That didnt not help cause my driver was already up to date at the time
