### ISSUE TITLE
White dots in-between blocks.

### ISSUE THREAD

**Issue by SlapHappyMC** [LunaPixelStudios/Fear-Nightfall#90]
### Describe the Bug

I'm experiencing white dots in-between blocks that flicker and move based on mouse movement (looking around).

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-03-26_22 39 44](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/165113918/306d34b4-192d-4eb4-b531-2258c4e17471)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Fear Nightfall v12

**Comment by chorbintime** [comment]
Please update your GPU drivers directly from your vendor's website. If this doesn't fix it, you can try disabling shaders or try a different shader
