### ISSUE TITLE
Suffocation 

### ISSUE THREAD

**Issue by Smewhey** [LunaPixelStudios/Fear-Nightfall#91]
### Describe the Bug

When host of lan world sits all other players suffocate when standing up after crawling.

### Reproduction Steps

1. Host sit
2. second player crawls
3. second player stands
4. Suffocation no breathing

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V12

**Comment by chorbintime** [comment]
LAN is unsupported and is likely to cause world corruption. Please host a server normally using the serverpack files on the modpack page.
