### ISSUE TITLE
Modpack crashes at the very end of loading. 

### ISSUE THREAD

**Issue by nccross** [LunaPixelStudios/Fear-Nightfall#93]
### Describe the Bug

I'm trying to run it through the curse forge app, and every time I hit play it crashes once it seems like it's done loading. I'm running v12, and have tried v11, v11.5, and v11.5 HF. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

MacOS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
I can't help if you dont provide logs. Send the one named "latest" in the logs folder or send the crash report in the crash reports folder

**Comment by fourhundredfour** [comment]
The problem occurs when you play on an Apple Silicon chip. Just delete the shader in the shaderpacks folder and then it will work.
