### ISSUE TITLE
Herobrine's signs are not loading correctly

### ISSUE THREAD

**Issue by OceanSnipe17** [LunaPixelStudios/Fear-Nightfall#94]
### Describe the Bug

When Herobrine leaves a sign, the message on the sign is not loading correctly.

I will also post this on the End of Herobrine mod's Github.

### Reproduction Steps

1. Wait for Herobrine to place a sign
2. Read the sign

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/46897556/634e8661-023a-4589-9056-e6ac026b07d9)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Other Mods

All the mods in the modpack plus the [Faster Ladder Climbing mod](https://www.curseforge.com/minecraft/mc-mods/faster-ladder-climbing) version 0.2.7 with base configuration.

**Comment by chorbintime** [comment]
more of an issue on the herobrine mod's side, but i appreciate you crossposting it here. will keep in mind & track the issue
