### ISSUE TITLE
Can't run FNv12 on Forge Server 1.19.2

### ISSUE THREAD

**Issue by De-Arc** [LunaPixelStudios/Fear-Nightfall#96]
### Describe the Bug

Can't run Fear Nightfall on forge server 1.19.2. Please help. logs:

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/De-Arc/5a596d904cda4b3f3ba1ecfaa135d1f5

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
How did you install & setup the server?

**Comment by De-Arc** [comment]
> How did you install & setup the server?

I use minecraft hosting services. I can ask support of hosting for all the information about their server if necessary. Also i can send any file from that server if u need it to help me.
![Безымянный](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/165938868/190a7299-8b04-4076-b6e8-a1f389a4fe15)

**Comment by De-Arc** [comment]
> How did you install & setup the server?

Any ideas?

**Comment by chorbintime** [comment]
> > How did you install & setup the server?
> 
> I use minecraft hosting services. I can ask support of hosting for all the information about their server if necessary. Also i can send any file from that server if u need it to help me. ![Безымянный](https://private-user-images.githubusercontent.com/165938868/319521405-190a7299-8b04-4076-b6e8-a1f389a4fe15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODk0NDMsIm5iZiI6MTcxMjQ4OTE0MywicGF0aCI6Ii8xNjU5Mzg4NjgvMzE5NTIxNDA1LTE5MGE3Mjk5LThiMDQtNDA3Ni1iNmU4LWExZjM4OWE0ZmUxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxMTI1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTgxNTZiZTQwOWE4NWU0Y2E0NThjZGY3YjEzOGVlNjE2MzBlZmRjYjE4NWQ4MzQ4NDRjYzYzNzAwOGQ0ODRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OhbWhcLgpofrJNSjRdZDZCQq8K4BCom9R_qT6NYbeT8)

specifically, what server host are you using? "minecraft hosting services" doesnt answer my question, unless there is a server host under that name
