### ISSUE TITLE
Game crashes upon loading existing worlds and generating new worlds. 

### ISSUE THREAD

**Issue by nccross** [LunaPixelStudios/Fear-Nightfall#97]
### Describe the Bug

Game no longer crashes when loading when I remove the shader, but now instead crashes one I attempt to generate a new world or load an existing one. I have attached the crash log this time to make things easier for you, apologies for not doing so earlier. Thanks for your help, appreciate it. 

[latest.log](https://github.com/LunaPixelStudios/Fear-Nightfall/files/14876969/latest.log)

### Reproduction Steps

1.
2.
3.
...

### Operating System

MacOS (M1 chip, not Intel)

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
Do you have a file named hs_err_pid anywhere in your modpack files?

**Comment by nccross** [comment]
yes, is that a file you need? i can attach it if so

**Comment by chorbintime** [comment]
yes, please send it

**Comment by Jorks1** [comment]
how exactly was the problem resolved

**Comment by chorbintime** [comment]
it wasnt resolved, i just never received a response so the issue was closed
