### ISSUE TITLE
Chunks load very slow

### ISSUE THREAD

**Issue by Daddy-ent** [LunaPixelStudios/Fear-Nightfall#98]
### Describe the Bug

Every time i load up a new world or play in a existing one new chunks load extremely slow. even when im just walking around the chunks cant keep up. Ive allocated 8 gb of ram, but i also tried giving it more but it doesnt do anything. Setting chunk loading to multithreading barely does anything as well, and same goes for disabling fog. I havent added any other mods or shaders. I dont experience this with any other modpack.
my specs are r9 5900x, 3080, 32gb ram

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

**Comment by chorbintime** [comment]
Follow the performance guide https://rpg.prominence.wiki/performance-guide
