### ISSUE TITLE
Chat Validation Failure 

### ISSUE THREAD

**Issue by StryderVR** [LunaPixelStudios/Fear-Nightfall#99]
### Describe the Bug

Any user that uses /msg or any dming feature in server causes everyone in game to get disconnected with the error "Chat Validation Error"
It rarely does it when using public chat as well
### Reproduction Steps

1.Open chat
2.Use /msg or any private message command 
3.Everyone gets kicked
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Fear-Nightfall/assets/54478468/0d4a2e34-06cc-4c90-8e80-f75db41ae955)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V12 (Latest)

**Comment by chorbintime** [comment]
does updating/removing "no chat reports" fix it? also, does it happen when the player is opped?

**Comment by StryderVR** [comment]
No Chat Reports wasn't installed in to the modpack or wasn't included with installation but when an opped player uses chatting commands it doesn't boot other than just non-opped being where it kicks every player including opped

**Comment by chorbintime** [comment]
Can you reproduce this issue then send the latest.log file?
